# 이메일
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jayong6652@gmail.com
    password: jplh wsms xkrx ghyk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true